### ISSUE TITLE
This is not enough protection/security. Use the XSS filter from CodeIgniter instead. Easy to copy paste.

### ISSUE THREAD

**Issue by digitalhuman** [nessphp/application#1]
https://github.com/nessphp/application/blob/f5c3541a26c24a9527282fa8870447b49debd949/Ness/Forms/Form.php#L168

**Comment by sinansalih** [comment]
Hi digitalhuman

if you check the line 460 on FormElements class you csn realise we use Sha1 encryption for xss protection.

htmlspecialchars is just used to prevent some basic tricks you can active xss filter by using FormElements class.
